server:
  port: 8080
 
spring:
  datasource:
    username: gzf_base
    password: gzf_base
    url: jdbc:mysql://localhost:3306/gzf_base?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.shkj.bean
 
#showSql
logging:
  level:
    com:
      example:
        mapper:debug