server:
  port: 8080

jasypt:
  encryptor:
    password: 123456
    
 #useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
spring:
  datasource:
    databasemaster:
      #type: org.apache.tomcat.jdbc.pool.DataSource 
      username: work_log_report
      #password: wlr@123 
      password: ENC(bDUFi3u/sGod3Dan3xDViw==)
      jdbc-url: jdbc:mysql://129.204.226.146:3306/work_log_report?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false     
      driver-class-name: com.mysql.jdbc.Driver 
      connection-timeout: 30000
      idle-timeout: 120000
      maxLifetime: 1200000
      minimum-idle: 10
      maximum-pool-size: 20
      leakDetectionThreshold: 5000         
    databaseslave:
      username: testdb
      password: testdb@123
      jdbc-url: jdbc:mysql://129.204.226.146:3306/testdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false     
      driver-class-name: com.mysql.jdbc.Driver
      #type: org.apache.tomcat.jdbc.pool.DataSource
      connection-timeout: 30000
      idle-timeout: 120000
      maxLifetime: 1200000
      minimum-idle: 10
      maximum-pool-size: 20
      leakDetectionThreshold: 5000  
 
 
sysParam: 
  pubKey: BDD2bV50fogKfCTQvj253OZTEPbopv0o6hxh+2L1e16Ph2Fuon16X7Paak43ScBFrSYcgNt1wIhtW0CGyRAjkOk=     