spring:
  profiles:
    active: dev
    
logging.config:
    classpath:logback-spring.xml
    
pagehelper:
    helperDialect: mysql
    reasonable: true #开启优化，<1页返回第一页
    supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
    pageSizeZero: false #pageSize=0 返回所有
    params: count=countSql
    
