server:
  port: 8080
 
 #useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
spring:
  datasource:
    username: work_log_report
    password: wlr@123
    url: jdbc:mysql://129.204.226.146:3306/work_log_report?autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.shkj.bean
 
#showSql
logging:
  level:
    com:
      shkj:
        mapper:debug